### ISSUE TITLE
libgdbm3 doesn't exist on Ubuntu 18.04

### ISSUE THREAD

**Issue by cornuwel** [jdowning/puppet-rbenv#78]
Hi,

manifests/deps/debian.pp requires libgdbm3, but it doesn't exist in Ubuntu 18.04.

`Error: /Stage[main]/Rbenv::Deps::Debian/Package[libgdbm3]/ensure: change from 'purged' to 'present' failed: Execution of '/usr/bin/apt-get -q -y -o DPkg::Options::=--force-confold install libgdbm3' returned 100: Reading package lists...
Building dependency tree...
Reading state information...
E: Unable to locate package libgdbm3`

Ruby compiles fine with libgdbm5.

**Comment by scotje** [comment]
`libgdbm-dev` seems to depend on the correct version of `libgdbm` on the various Debian variants that I spot-checked, so maybe we can just remove the direct dependency entirely and just let it resolve through `libgdbm-dev`?

**Comment by jdowning** [comment]
Fixed in #82
