### ISSUE TITLE
--no-ri and --no-rdoc are removed in ruby 2.6+

### ISSUE THREAD

**Issue by agitelzon** [jdowning/puppet-rbenv#80]
Ruby 2.6.0, https://www.ruby-lang.org/en/news/2018/12/25/ruby-2-6-0-released/ removes the `--ri` and `--rdoc` options and their `--no-` variants. 

>Please use the `--document` and `--no-document` options instead."

The gem install manifest needs to be updated to use `--no-document` when ruby is newer than version 2.5.

**Comment by abegosum** [comment]
Unfortunately, this is dependent on the version of rubygems, not Ruby specifically (ruby 2.6 or greater just happens to come with rubygems 3.0.1 out of the gate).

I'm working on way to handle the if branching in shell to get around this issue.

**Comment by abegosum** [comment]
Filed PR: https://github.com/jdowning/puppet-rbenv/pull/81

**Comment by ezziwa** [comment]
Thanks it helped
