### ISSUE TITLE
Specifying the rubygems version

### ISSUE THREAD

**Issue by denzelem** [jdowning/puppet-rbenv#87]
Hello,

I was searching for a built-in way to specify the Rubygems version with `puppet-rbenv`. Is this already supported or is there a reason why it is not supported?

Example: When I install Ruby `2.6.6` I will have the default bundled Rubygems version `3.0.3`. As this version has many bugs in combination with Bundler 2, I want to upgrade the Rubygems version to `3.1.2`.

```ruby
class { 'rbenv': }
rbenv::plugin { [ 'rbenv/rbenv-vars', 'rbenv/ruby-build' ]: }
rbenv::build { '2.6.6': global => true }

# A workaround might look somehow like this
exec { "upgrade rubygems to version 3.1.2":
  command => "/bin/bash -ic 'gem update --system 3.1.2'",
}

rbenv::gem { 'bundler': version => '2.1.4', ruby_version => '2.6.6' }
```

Thanks!

**Comment by jdowning** [comment]
@denzelem No, there is not a built-in way to do this currently. If you would like to submit a PR, I'd be happy to consider it for inclusion here. I'm thinking we should add a parameter to `rbenv::build` that performs the exec you outlined in your example, similar to how [global](https://github.com/jdowning/puppet-rbenv/blob/b8ae89834bf23955f3164934c632264d870795fd/manifests/build.pp#L162-L170) can be specified.
