### ISSUE TITLE
Cannot install for sudo

### ISSUE THREAD

**Issue by avisecag** [jdowning/puppet-rbenv#93]
The module works fine for all I can tell, but I do not understand how it chooses the user for which to install. I thought if I  installed it globally, then sudo should also have it set up, but that's not the case. And that's even though the puppet agent installing it is itself running as sudo.

The setup in my manifest is very straightforward, mostly from the documentation:
```
  class { 'rbenv': }
  rbenv::plugin { [ 'rbenv/rbenv-vars', 'rbenv/ruby-build' ]: }
  rbenv::build { '2.5.8': global => true }
```

With the normal user, things are fine:
```
host:~ $ ruby --version
ruby 2.5.8p224 (2020-03-31 revision 67882) [armv7l-linux-eabihf]
host:~ $ rbenv --version
rbenv 1.1.2-44-gd604acb
```
However, for root nothing is set up. The old version is still being found, and rbenv is unknown:
```
host:~ $ sudo ruby --version
ruby 2.3.3p222 (2016-11-21) [arm-linux-gnueabihf]
host:~ $ sudo rbenv --version
sudo: rbenv: command not found
```
This is a bit frustrating, because puppet is really the only thing actually using ruby on that system, and since it runs as root, it doesn't get the new version.

**Comment by jdowning** [comment]
This is because the `root` user does not have `rbenv` in its `PATH`. This puppet module adds a [helper](https://github.com/jdowning/puppet-rbenv/blob/master/templates/rbenv.sh) to your current user's profile.

To get `rbenv` to work with sudo, you'll need to make sure the `root` user `PATH` has rbenv included.
