### ISSUE TITLE
New tag and Forge release?

### ISSUE THREAD

**Issue by jantman** [jdowning/puppet-rbenv#94]
The rbenv::build ``rubygems_version`` parameter is extremely helpful for installing older rubies. It's in master, but not in the latest tagged release or on the Forge. Would it be possible to get a new release cut and uploaded?

**Comment by jdowning** [comment]
Sorry for the late reply here! I've published a new release and tag:

https://forge.puppet.com/modules/jdowning/rbenv/3.0.0/readme
https://github.com/jdowning/puppet-rbenv/releases/tag/3.0.0
